### ISSUE TITLE
$.doc() marked 编译报错

### ISSUE THREAD

**Issue by nimojs** [nimojs/nodeajax#27]
在 app.js 中书写如下代码
<pre>
$.doc(function (){/*
# 特殊说明

所有JSON中以下划线为前缀均为注释，用于给说明对应属性。后端不需要将 `_` 前缀的属性返回
例如文档中写：
```
{
    "money": 13,
    "_money": "报名费用"
}
```
后端只需要输出 `{"money":13}`
*/})
</pre>
会导致报错

```
/Users/nimojs/Documents/code/nodeajax/node_modules/marked/lib/marked.js:1215
    throw e;
          ^
Error: Unknown language: "undefined"
Please report this to https://github.com/chjj/marked.
    at Object.highlight (/Users/nimojs/Documents/code/nodeajax/node_modules/highlight.js/lib/highlight.js:439:13)
    at Object.marked.setOptions.highlight (/Users/nimojs/Documents/code/nodeajax/src/init.js:120:29)
    at Renderer.code (/Users/nimojs/Documents/code/nodeajax/node_modules/marked/lib/marked.js:759:28)
    at Parser.tok (/Users/nimojs/Documents/code/nodeajax/node_modules/marked/lib/marked.js:979:28)
    at Parser.parse (/Users/nimojs/Documents/code/nodeajax/node_modules/marked/lib/marked.js:924:17)
    at Function.Parser.parse (/Users/nimojs/Documents/code/nodeajax/node_modules/marked/lib/marked.js:911:17)
    at marked (/Users/nimojs/Documents/code/nodeajax/node_modules/marked/lib/marked.js:1207:19)
    at null._onTimeout (/Users/nimojs/Documents/code/nodeajax/src/init.js:124:28)
    at Timer.listOnTimeout (timers.js:110:15)
```

**Comment by nimojs** [comment]
原因是 `highlight.js` 没有检测到语言类型，通过如下判断解决此问题
```
marked.setOptions({
            highlight: function (code, lang, callback) {
                // Ref: https://github.com/nimojs/nodeajax/issues/27
                if (lang) {
                    return hljs.highlight(lang, code).value
                }
                else {
                    return hljs.highlightAuto(code).value
                }
            }
        })
```
